// This file is generated by the rs-bump-version script

#pragma once

#include <string>
#include <array>

namespace std {

    inline std::array<int, 3> version() noexcept {
        return {{ 1, 0, 2 }};
    }

    inline std::string version_string() {
        return "1.0.2";
    }

}
